name: Build Shiny Docker Image

on:
  push:
    paths:
        - shiny-app/**
        - .**/build_shiny_docker.yml
  schedule:
    - cron: '0 19 * * 6'

env:
    DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
    DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:shiny-app/docker"
          platforms: linux/amd64
          push: true
          cache-from: type=registry,ref=vazome/appsilon-homework:latest
          cache-to: type=inline
          tags: vazome/appsilon-homework:latest